spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      # 初始化大小 ，最大，最小
      initial-size: 10 #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      min-idle: 10     #最小连接池数量
      maxActive: 100   #最大连接池数量
      # 配置获取连接等待超时时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunMillis: 60000
      # 配置一个连接在池中的最小生存时间,单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnRuturn: false
      # 打开 PSCache,并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPrepareStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters,去掉后监控界面sql将无法统计,'wall' 用于防火墙
      filters: stat,wall,log4j
      # 通过 connectProperties 属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.showSqlMillis=5000
      # 合并多个 DruidDataSource的监控数据
      # useGlobalDataSourceStat=true

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html

  servlet:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb
#  data:
#    elasticsearch:
#      #集群名。(默认值: elasticsearch)
#      cluster-name: elasticsearch
#      #集群其他节点地址列表，用逗号分隔。如果没有指定，就启动一个客户端节点。默认 9300 是 Java 客户端的端口。
#      cluster-nodes: 127.0.0.1:9300
#
#      #开启 Elasticsearch 仓库。(默认值:true。)
#      repositories:
#        enabled: true

#  elasticsearch:
#    jest:
#      proxy:
#        host: localhost
#        port: 9300



# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    typeAliasesPackage: com.cycloneboy.videocodec.entity
    #config-location: classpath:mybatis.xml
    configuration:
          map-underscore-to-camel-case: true  #使用驼峰法映射属性

# Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  typeAliasesPackage: com.cycloneboy.videocodec.entity
  configuration:
    map-underscore-to-camel-case: true  #使用驼峰法映射属性
    cache-enabled: false
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #Sequence序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx

server:
  tomcat:
    uri-encoding: utf-8
  port: 18080



